#!/usr/bin/env python3

# Read date and time from RTC chip

import pyRPiRTC

rtc = pyRPiRTC.DS1302(clk_pin=11, data_pin=13, ce_pin=15)

try:
    # read date and time from RTC chip
    dt = rtc.read_datetime()
    print('Get RTC time is %s' % dt.strftime('%Y-%m-%d %H:%M:%S.%fZ'))
finally:
    # clean close
    rtc.close()
