#!/usr/bin/env python3

# Write RPi current date and time (UTC time) to RTC chip

import datetime
import pyRPiRTC

rtc = pyRPiRTC.DS1302(clk_pin=11, data_pin=13, ce_pin=15)

try:
    # write date and time from system to RTC chip (in UTC)
    dt_write = datetime.datetime.utcnow()
    # update rtc
    rtc.write_datetime(dt_write)
    # check update is good
    dt_read = rtc.read_datetime()
    if -2 < (dt_write - dt_read).total_seconds() < +2:
        print('Set RTC time is %s' % dt_write.strftime('%Y-%m-%d %H:%M:%S.000000Z'))
    else:
        exit('unable to set RTC time')
finally:
    rtc.close()
