#!/usr/bin/env python3

# read date and time from RTC chip, return ISO 8601 UTC string
# assume DS1302 contain UTC time and not local

import sys
import pyRPiRTC
import sys
from datetime import datetime

rtc = pyRPiRTC.DS1302(clk_pin=11, data_pin=13, ce_pin=15)
try:
    # write date and time from system to RTC chip (in UTC) 
    if len(sys.argv)< 2:
        exit("use: ds1302_set_utc_from_string '09/19/18 13:55:26' ")
    dt_write = datetime.strptime(sys.argv[1], '%m/%d/%y %H:%M:%S')
    # update rtc
    rtc.write_datetime(dt_write)
    # check update is good
    dt_read = rtc.read_datetime()
    if -2 < (dt_write - dt_read).total_seconds() < +2:
        print(dt_write.strftime('%Y-%m-%dT%H:%M:%SZ'))
    else:
        exit('unable to set RTC time')
except ValueError:
    sys.exit('error with RTC chip, check wiring')
finally:
    rtc.close()
